apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziggle-fe
  labels:
    app: ziggle-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziggle-fe
  template:
    metadata:
      labels:
        app: ziggle-fe
    spec:
      containers:
        - name: ziggle-fe
          image: minjuncho/ziggle-fe:12
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ziggle-fe-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: ziggle-fe
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ziggle-fe
#   namespace: blms
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`www.blms.transceiver.api.local.example.com`)
#       kind: Rule
#       services:
#         - name: ziggle-fe-service
#           port: 80
#     - match: Host(`blms.transceiver.api.local.example.com`)
#       kind: Rule
#       services:
#         - name: ziggle-fe-service
#           port: 80
#       middlewares:
#         - name: blms-headers
# tls:
#   secretName: local-example-com-tls
