apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziggle-ai
  labels:
    app: ziggle-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ziggle-ai
  template:
    metadata:
      labels:
        app: ziggle-ai
    spec:
      containers:
        - name: ziggle-ai
          image: minjuncho/ziggle-ai:9
          envFrom:
            - secretRef:
                name: blms-gpt-api-key-yaml
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ziggle-ai-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: ziggle-ai
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ziggle-ai
#   namespace: blms
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`www.blms.transceiver.api.local.example.com`)
#       kind: Rule
#       services:
#         - name: ziggle-ai-service
#           port: 80
#     - match: Host(`blms.transceiver.api.local.example.com`)
#       kind: Rule
#       services:
#         - name: ziggle-ai-service
#           port: 80
#       middlewares:
#         - name: blms-headers
# tls:
#   secretName: local-example-com-tls
